install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose


script:
  - ls -lah
  - docker-compose up -d dbbackup
  - docker exec dockerpgbackups_dbbackup_1 date --set="2012-6-29 10:59.59 PM"
  - wait 4
  - ls -lah backups/*
  - if [[ ! -f "backups/2012/June/foo.dmp" ]]; then exit 1; fi
notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true

  email:
    - tim@kartoza.com
