# This is for testing on travis only
# For production we recommend to rather use
# image: kartoza/pg-backup
# in the dbbackup service
db:
  image: kartoza/postgis
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASS=docker

dbbackup:
  build: .
  volumes:
    - ./backup:/backup
  environment:
    - DUMPPREFIX=watchkeeper
    - POSTGRES_HOST=db
    - POSTGRES_DBNAME=gis
    - POSTGRES_USER=docker
    - POSTGRES_PASS=docker
    - POSTGRES_PORT=5432
  links:
    - db:db
